steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=cloudbuild/settings.enc
  - --plaintext-file=/root/.m2/settings.xml
  - --location=global
  - --keyring=rckms-cloud-build
  - --key=github
  volumes:
  - name: 'm2'
    path: /root/.m2
- name: 'maven:3.6.1-jdk-8'
  entrypoint: 'mvn'
  args: ['-q', '-DskipTests', 'clean', 'install']
  dir: '.'
  volumes:
  - name: 'm2'
    path: /root/.m2
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/opencds-service:$BRANCH_NAME', '-f', 'docker/Dockerfile', '.']
  dir: '.'
images: ['gcr.io/$PROJECT_ID/dss']
timeout: 900s
