steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.gcp.config/settings.enc
  - --plaintext-file=/root/.m2/settings.xml
  - --location=global
  - --keyring=main
  - --key=gcb_key
  volumes:
  - name: 'm2'
    path: /root/.m2
- name: 'maven:3-jdk-8-slim'
  id: build
  entrypoint: 'mvn'
  args: ['clean', 'install']
  volumes:
  - name: 'm2'
    path: /root/.m2

- name: 'maven:3-jdk-8-slim'
  id: deploy
  entrypoint: 'mvn'
  args: ['deploy', '-DaltDeploymentRepository=support.hln.com-snapshots::default::https://support.hln.com/artifactory/libs-snapshot-local']
  volumes:
  - name: 'm2'
    path: /root/.m2

# trigger opencds ice build
- name: gcr.io/hln-internal/gsutil-beta:master
  dir: /root
  entrypoint: gcloud
  args: ['--quiet', 'beta', 'builds', 'triggers', 'run', '--branch', 'DEV', '445d0670-ae92-44fc-819c-2182e3b3d035']

# trigger opencds rckms build
- name: gcr.io/hln-internal/gsutil-beta:master
  dir: /root
  entrypoint: gcloud
  args: ['--quiet', 'beta', 'builds', 'triggers', 'run', '--branch', $BRANCH_NAME, 'a8c4e364-b6f2-4e1b-843d-1d9ad7ea10a']
