steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.gcp.config/settings.enc
  - --plaintext-file=/root/.m2/settings.xml
  - --location=global
  - --keyring=main
  - --key=gcb_key
  volumes:
  - name: 'm2'
    path: /root/.m2
- name: 'maven:3-jdk-8-slim'
  id: build
  entrypoint: 'mvn'
  args: ['clean', 'install']
  volumes:
  - name: 'm2'
    path: /root/.m2

- name: 'maven:3-jdk-8-slim'
  id: deploy
  entrypoint: 'mvn'
  args: ['deploy', '-DaltDeploymentRepository=support.hln.com-snapshots::default::https://support.hln.com/artifactory/libs-release-local']
  volumes:
  - name: 'm2'
    path: /root/.m2

# trigger opencds ice build
- name: gcr.io/cloud-builders/curl
  entrypoint: 'sh'
  args: ['-c', 'curl -X POST https://cloudbuild.googleapis.com/v1/projects/cdsframework/triggers/de07e3ef-8d51-4591-b7a9-afcc24dff544:run']

# trigger opencds rckms build
- name: gcr.io/cloud-builders/curl
  entrypoint: 'sh'
  args: ['-c', 'curl -X POST https://cloudbuild.googleapis.com/v1/projects/hln-rckms/triggers/a8c4e364-b6f2-4e1b-843d-1d9ad7ea10a:run']
